In [31]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix

In [4]:
df_lab_geo = pd.read_csv('data/labGeo/dados_entrada_lab_geo-2024_01_19.csv', encoding='iso-8859-1')

In [10]:
df_lab_geo.columns

Index(['V0003', 'V0004', 'CODSET', 'CODMUN', 'NOMEMUN', 'NOMERM', 'SITUACAO',
       'VAR12', 'HAB1', 'HAB2', 'HAB3', 'HAB4', 'HAB5', 'HAB6', 'HAB7', 'CHE1',
       'CHE2', 'CHE3', 'CHE4', 'CHE5', 'CHE6', 'CHE7', 'HAB8', 'HAB9', 'TIPO'],
      dtype='object')

In [17]:
df_lab_gem_RMSP = df_lab_geo.loc[df_lab_geo.NOMERM == 'RM de São Paulo', ['V0003', 'V0004', 'VAR12', 
                  'HAB1', 'HAB2', 'HAB3', 'HAB4', 'HAB5', 'HAB6', 'HAB7', 
                  'CHE1', 'CHE2', 'CHE3', 'CHE4', 'CHE5', 'CHE6', 'CHE7', 
                  'HAB8', 'HAB9', 'TIPO']].fillna(0)

In [18]:
df_lab_gem_RMSP

V0003  V0004  VAR12      HAB1      HAB2      HAB3       HAB4  \
69402    134      0  424.0  0.000000  1.492537  0.000000   0.746269   
69403    149      1  589.0  0.000000  0.000000  0.000000   0.000000   
69404    131      1  479.0  0.763359  0.000000  0.000000   1.526718   
69405    170      0  654.0  0.000000  0.588235  0.000000   2.352941   
69406    181      0  572.0  0.000000  1.104972  0.833333   0.000000   
...      ...    ...    ...       ...       ...       ...        ...   
90626    172      0  701.0  0.000000  0.000000  0.000000  22.093023   
90627    209      0  885.0  0.000000  0.000000  0.000000   1.913876   
90628    154      4  590.0  0.000000  0.649351  0.847458  11.038961   
90629    209      2  810.0  0.478469  0.478469  0.000000   2.392344   
90630    175      2  592.0  0.571429  0.571429  0.000000  66.857143   

            HAB5      HAB6      HAB7       CHE1       CHE2      CHE3  \
69402   6.716418  0.746269  0.000000   8.955224  11.940299  0.000000   
69403   1.342282  0.000000  0.000000  12.080537  12.751678  0.671141   
69404   0.763359  0.000000  0.000000   7.633588  12.213740  0.763359   
69405   0.000000  0.000000  0.000000   8.235294  11.176471  0.000000   
69406   0.000000  0.000000  0.000000  20.994475   3.314917  0.000000   
...          ...       ...       ...        ...        ...       ...   
90626   2.906977  1.744186  0.581395  19.186047  11.627907  0.581395   
90627  18.181818  0.478469  0.000000  23.923445  13.875598  0.956938   
90628   9.090909  0.000000  0.000000  18.831169  16.883117  0.649351   
90629   3.349282  3.349282  0.000000  18.181818  10.047847  0.956938   
90630   2.285714  1.714286  4.000000  17.142857   9.714286  1.142857   

            CHE4      CHE5       CHE6         CHE7      HAB8      HAB9  TIPO  
69402  61.940299  5.744361  46.268657   999.462687  3.164179  1.507576     0  
69403  67.785235  5.838926  40.268456  1029.597315  3.953020  1.492188     0  
69404  51.908397  6.744186  35.114504  1161.068702  3.656489  1.832061     0  
69405  51.764706  7.227545  34.117647  1367.176471  3.847059  2.136905     0  
69406  60.220994  6.680000  40.883978   979.640884  3.160221  1.505882     0  
...          ...       ...        ...          ...       ...       ...   ...  
90626  73.837209  5.354651  55.813953   509.401163  4.075581  1.201183     0  
90627  71.291866  5.200957  64.114833   418.545455  4.234450  1.183575     0  
90628  68.831169  5.176471  58.441558   581.006494  3.831169  1.177632     0  
90629  71.291866  5.244019  59.330144   424.100478  3.875598  1.064677     0  
90630  59.428571  6.874286  41.142857  1218.902857  3.382857  1.854651     0  

[21229 rows x 20 columns]

In [19]:
df_lab_gem_RMSP.TIPO.value_counts()

TIPO
0    19176
1     2053
Name: count, dtype: int64

In [34]:
X = df_lab_gem_RMSP.drop(columns=['TIPO'])
y = df_lab_gem_RMSP.TIPO

In [76]:
clf = LinearDiscriminantAnalysis(n_components=1)
clf.fit(X, y)

LinearDiscriminantAnalysis(n_components=1)

In [77]:
np.unique(clf.predict(X), return_counts=True)

(array([0, 1]), array([19583,  1646]))

In [78]:
clf.score(X, y)

0.9394695934806161

In [79]:
cf_matrix = confusion_matrix(y, clf.predict(X))

In [83]:
cf_matrix

array([[18737,   439],
       [  846,  1207]])

In [81]:
clf.predict_proba(X)

array([[9.89321306e-01, 1.06786936e-02],
       [9.91068241e-01, 8.93175932e-03],
       [9.91114045e-01, 8.88595521e-03],
       ...,
       [9.39747338e-01, 6.02526624e-02],
       [9.89952534e-01, 1.00474656e-02],
       [9.99926785e-01, 7.32151107e-05]])

In [82]:
clf.predict(X)

array([0, 0, 0, ..., 0, 0, 0])

In [84]:
clf.decision_function(X)

array([-4.52876865, -4.70917   , -4.71435764, ..., -2.74706429,
       -4.59033657, -9.52203551])